//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PolicyType { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string AdditionalName1 { get; set; }
        public string AdditionalName2 { get; set; }
        public string AdditionalName3 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
